var store = {
  state: {
    products: [
      {
        id: 1,
        brand: "Lenovo",
        title: "Notebook Lenovo Ideapad S145",
        description: "Notebook Lenovo Ideapad S145, Intel Core i7-1065G7, 8GB, SSD 256GB, 15.6´ Full HD, Dolby Audio, Windows 10 Home, Prata - 82DJ0000BR",
        price: 44000,
        count: 100,
        status: "Active",
        images: [],
      },
      {
        id: 2,
        brand: "WD",
        title: "SSD WD Blue, 500GB",
        description: "SSD WD Blue, 500GB, SATA, Leitura 560MB/s, Gravação 530MB/s - WDS500G2B0A",
        price: 510,
        count: 500,
        status: "Active",
        images: [],
      },
      {
        id: 3,
        brand: "Microsoft",
        title: "Controle Microsoft Xbox",
        description: "Controle Microsoft Xbox, Sem Fio, Preto - QAT-00007",
        price: 420,
        count: 500,
        status: "Active",
        images: [],
      },
      {
        id: 4,
        brand: "Kingston",
        title: "SSD Kingston A400, 480GB",
        description: "SSD Kingston A400, 480GB, SATA, Leitura 500MB/s, Gravação 450MB/s - SA400S37/480G",
        price: 460,
        count: 800,
        status: "Active",
        images: [],
      }, 
      {
        id: 5,
        brand: "LG",
        title: 'Monitor LG LED 27"',
        description: 'Monitor LG LED 27", 4K, UHD, IPS, HDMI/DisplayPort, AMD Radeon FreeSync, Altura Ajustável, VESA - 27MU58P-B.AWZ',
        price: 1800,
        count: 80,
        status: "Active",
        images: [],
      }, 
      {
        id: 6,
        brand: "Acer",
        title: "Monitor Gamer Acer LED 23.6´",
        description: "Monitor Gamer Acer LED 23.6´ Full HD, HDMI/DisplayPort, Free Sync, 165Hz, 0.5ms, Inclinação Ajustável, Preto/Vermelho - KG241Q Sbiip",
        price: 1320,
        count: 50,
        status: "Active",
        images: [],
      }, 
      /* 
      {
        id: ,
        brand: "",
        title: "",
        description: "",
        price: ,
        count: ,
        status: "Active",
        images: [],
      }, 
      */
    ],
  },
};